fake error

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -38,7 +38,33 @@ jobs:
             - name: installing dependencis
               run: |
                    python -m pip install --upgrade pip
-                   pip install -r requirements.txt
+                   pip install -r requirements.txt 
+            - name: fake error with message
+              run: |
+                  echo "::error::This is a fake error for testing"
+                  exit 1
+            - name: building project
+              run: |
+                  echo "Building project"
+
+    deploy:
+        runs-on: ubuntu-latest
+        needs: build
+        steps:
+            - name: checkout repository
+              uses: actions/checkout@v5
+            - name: installing python
+              uses: actions/setup-python@v5
+              with:
+                   python-version: '3.13'
+            - name: installing dependencis
+              run: |
+                   python -m pip install --upgrade pip
+                   pip install -r requirements.txt 
+            - name: fake error with message
+              run: |
+                  echo "::error::This is a fake error for testing"
+                  exit 1
             - name: building project
               run: |
                   echo "Building project"
